REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA final_project FROM final_app;
REVOKE USAGE ON SCHEMA final_project FROM final_app;
REVOKE ALL PRIVILEGES ON DATABASE joel FROM final_app;
DROP USER IF EXISTS final_app;
